/**
 * @boringnode/pluralize
 *
 * @license MIT
 * @copyright BoringNode
 */

import { pattern } from '../../pattern.js'
import type { Substitution } from '../../substitution.js'
import type { Transformation } from '../../transformation.js'

export function getSingular(): Transformation[] {
  return [
    { pattern: pattern('(s)tatuses$'), replacement: '$1tatus' },
    { pattern: pattern('(s)tatus$'), replacement: '$1tatus' },
    { pattern: pattern('(c)ampus$'), replacement: '$1ampus' },
    { pattern: pattern('^(.*)(menu)s$'), replacement: '$1$2' },
    { pattern: pattern('(quiz)zes$'), replacement: '$1' },
    { pattern: pattern('(matr)ices$'), replacement: '$1ix' },
    { pattern: pattern('(vert|ind)ices$'), replacement: '$1ex' },
    { pattern: pattern('^(ox)en'), replacement: '$1' },
    { pattern: pattern('(alias)(es)*$'), replacement: '$1' },
    { pattern: pattern('(buffal|her|potat|tomat|volcan)oes$'), replacement: '$1o' },
    {
      pattern: pattern('(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|viri?)i$'),
      replacement: '$1us',
    },
    { pattern: pattern('([ftw]ax)es'), replacement: '$1' },
    { pattern: pattern('(analys|ax|cris|test|thes)es$'), replacement: '$1is' },
    { pattern: pattern('(shoe|slave)s$'), replacement: '$1' },
    { pattern: pattern('(o)es$'), replacement: '$1' },
    { pattern: pattern('ouses$'), replacement: 'ouse' },
    { pattern: pattern('([^a])uses$'), replacement: '$1us' },
    { pattern: pattern('([m|l])ice$'), replacement: '$1ouse' },
    { pattern: pattern('(x|ch|ss|sh)es$'), replacement: '$1' },
    { pattern: pattern('(m)ovies$'), replacement: '$1ovie' },
    { pattern: pattern('(s)eries$'), replacement: '$1eries' },
    { pattern: pattern('([^aeiouy]|qu)ies$'), replacement: '$1y' },
    { pattern: pattern('([lr])ves$'), replacement: '$1f' },
    { pattern: pattern('(tive)s$'), replacement: '$1' },
    { pattern: pattern('(hive)s$'), replacement: '$1' },
    { pattern: pattern('(drive)s$'), replacement: '$1' },
    { pattern: pattern('(dive)s$'), replacement: '$1' },
    { pattern: pattern('(olive)s$'), replacement: '$1' },
    { pattern: pattern('([^fo])ves$'), replacement: '$1fe' },
    { pattern: pattern('(^analy)ses$'), replacement: '$1sis' },
    {
      pattern: pattern('(analy|diagno|^ba|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$'),
      replacement: '$1$2sis',
    },
    { pattern: pattern('(tax)a$'), replacement: '$1on' },
    { pattern: pattern('(c)riteria$'), replacement: '$1riterion' },
    { pattern: pattern('([ti])a$'), replacement: '$1um' },
    { pattern: pattern('(p)eople$'), replacement: '$1erson' },
    { pattern: pattern('(m)en$'), replacement: '$1an' },
    { pattern: pattern('(c)hildren$'), replacement: '$1hild' },
    { pattern: pattern('(f)eet$'), replacement: '$1oot' },
    { pattern: pattern('(n)ews$'), replacement: '$1ews' },
    { pattern: pattern('eaus$'), replacement: 'eau' },
    { pattern: pattern('^tights$'), replacement: 'tights' },
    { pattern: pattern('^shorts$'), replacement: 'shorts' },
    { pattern: pattern('s$'), replacement: '' },
  ]
}

export function getPlural(): Transformation[] {
  return [
    { pattern: pattern('(s)tatus$'), replacement: '$1tatuses' },
    { pattern: pattern('(quiz)$'), replacement: '$1zes' },
    { pattern: pattern('^(ox)$'), replacement: '$1en' },
    { pattern: pattern('([m|l])ouse$'), replacement: '$1ice' },
    { pattern: pattern('(matr|vert|ind)(ix|ex)$'), replacement: '$1ices' },
    { pattern: pattern('(x|ch|ss|sh)$'), replacement: '$1es' },
    { pattern: pattern('([^aeiouy]|qu)y$'), replacement: '$1ies' },
    { pattern: pattern('(hive|gulf)$'), replacement: '$1s' },
    { pattern: pattern('(?:([^f])fe|([lr])f)$'), replacement: '$1$2ves' },
    { pattern: pattern('sis$'), replacement: 'ses' },
    { pattern: pattern('([ti])um$'), replacement: '$1a' },
    { pattern: pattern('(tax)on$'), replacement: '$1a' },
    { pattern: pattern('(c)riterion$'), replacement: '$1riteria' },
    { pattern: pattern('(p)erson$'), replacement: '$1eople' },
    { pattern: pattern('(m)an$'), replacement: '$1en' },
    { pattern: pattern('(c)hild$'), replacement: '$1hildren' },
    { pattern: pattern('(f)oot$'), replacement: '$1eet' },
    { pattern: pattern('(buffal|her|potat|tomat|volcan)o$'), replacement: '$1oes' },
    {
      pattern: pattern('(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|vir)us$'),
      replacement: '$1i',
    },
    { pattern: pattern('us$'), replacement: 'uses' },
    { pattern: pattern('(alias)$'), replacement: '$1es' },
    { pattern: pattern('(analys|ax|cris|test|thes)is$'), replacement: '$1es' },
    { pattern: pattern('s$'), replacement: 's' },
    { pattern: pattern('^$'), replacement: '' },
    { pattern: pattern('$'), replacement: 's' },
  ]
}

export function getIrregular(): Substitution[] {
  return [
    { from: 'atlas', to: 'atlases' },
    { from: 'axe', to: 'axes' },
    { from: 'beef', to: 'beefs' },
    { from: 'brother', to: 'brothers' },
    { from: 'cafe', to: 'cafes' },
    { from: 'canvas', to: 'canvases' },
    { from: 'chateau', to: 'chateaux' },
    { from: 'child', to: 'children' },
    { from: 'cookie', to: 'cookies' },
    { from: 'corpus', to: 'corpora' },
    { from: 'cow', to: 'cows' },
    { from: 'criterion', to: 'criteria' },
    { from: 'curriculum', to: 'curricula' },
    { from: 'demo', to: 'demos' },
    { from: 'die', to: 'dice' },
    { from: 'domino', to: 'dominoes' },
    { from: 'echo', to: 'echoes' },
    { from: 'epoch', to: 'epochs' },
    { from: 'foot', to: 'feet' },
    { from: 'fungus', to: 'fungi' },
    { from: 'ganglion', to: 'ganglions' },
    { from: 'gas', to: 'gases' },
    { from: 'genie', to: 'genies' },
    { from: 'genus', to: 'genera' },
    { from: 'goose', to: 'geese' },
    { from: 'graffito', to: 'graffiti' },
    { from: 'hippopotamus', to: 'hippopotami' },
    { from: 'hoof', to: 'hoofs' },
    { from: 'human', to: 'humans' },
    { from: 'hypnosis', to: 'hypnoses' },
    { from: 'iris', to: 'irises' },
    { from: 'larva', to: 'larvae' },
    { from: 'leaf', to: 'leaves' },
    { from: 'lens', to: 'lenses' },
    { from: 'loaf', to: 'loaves' },
    { from: 'lumen', to: 'lumens' },
    { from: 'man', to: 'men' },
    { from: 'medium', to: 'media' },
    { from: 'memorandum', to: 'memoranda' },
    { from: 'money', to: 'monies' },
    { from: 'mongoose', to: 'mongooses' },
    { from: 'mosquito', to: 'mosquitoes' },
    { from: 'motto', to: 'mottoes' },
    { from: 'move', to: 'moves' },
    { from: 'mythos', to: 'mythoi' },
    { from: 'niche', to: 'niches' },
    { from: 'nucleus', to: 'nuclei' },
    { from: 'numen', to: 'numina' },
    { from: 'oasis', to: 'oases' },
    { from: 'octopus', to: 'octopuses' },
    { from: 'opus', to: 'opuses' },
    { from: 'ox', to: 'oxen' },
    { from: 'passerby', to: 'passersby' },
    { from: 'penis', to: 'penises' },
    { from: 'person', to: 'people' },
    { from: 'plateau', to: 'plateaux' },
    { from: 'runner-up', to: 'runners-up' },
    { from: 'sex', to: 'sexes' },
    { from: 'soliloquy', to: 'soliloquies' },
    { from: 'son-in-law', to: 'sons-in-law' },
    { from: 'specimen', to: 'specimens' },
    { from: 'syllabus', to: 'syllabi' },
    { from: 'testis', to: 'testes' },
    { from: 'thief', to: 'thieves' },
    { from: 'tooth', to: 'teeth' },
    { from: 'tornado', to: 'tornadoes' },
    { from: 'trilby', to: 'trilbys' },
    { from: 'turf', to: 'turfs' },
    { from: 'volcano', to: 'volcanoes' },
    { from: 'woman', to: 'women' },
    { from: 'zombie', to: 'zombies' },
  ]
}
